name: TimaHorse
version: '${project.version}'
main: ovh.rootkovskiy.timahorse.Main
authors: [ timurroot ]
description: Simple plugin that adds the ability to ride each other
website: www.rootkovskiy.ovh
commands:
  horse: {}
  horseon: {}
  horseoff: {}
